### ISSUE TITLE
[Feature Request] Parse external streams (file.contents at least) for variable tags

### ISSUE THREAD

**Issue by Kronopt** [jmartin82/mmock#107]
Hi,
I think it would be useful to parse external files for **variable tags**.
This way it would be possible to have the response contents outside the mock definition files and still be able to populate it with fake data.

If this is already possible, I can't seem to find how to do it.

## An example:

MMock definition:
```
request:
  method: GET
  path: "/"
response:
  statusCode: 200
  headers:
    Content-Type:
    - application/json
  body: "{{file.contents(test_payload.json)}}"
```

test_payload.json:
```
{"test": "{{fake.Brand}}"}
```

response:
```
{"test": "Zoozzy"}
```

Right now this is the response:
```
{"test": "{{fake.Brand}}"}
```

**Comment by jdvr** [comment]
Hi, is this still available? 

I am a newbie in Go but I will try to implement this feature, although I was thinking that maybe makes more sense to use another key, eg:

```yaml
request:
  method: GET
  path: "/"
response:
  statusCode: 200
  headers:
    Content-Type:
    - application/json
  bodyFilePath: test_payload.json
```

What do you think?
