### ISSUE TITLE
Feature Request: Support mocking an API that makes a HTTP request after some delay

### ISSUE THREAD

**Issue by mcintyre94** [jmartin82/mmock#110]
I'm opening this issue as a feature request because it'd be really useful, would appreciate feedback on whether this could be an appropriate extension.

I'd like to use mmock to mock an API where the contract is:

- Respond with HTTP 202 Accepted
- At some point later, make an API request to a given URL

---

The specific use case here is around APIs orchestrated by AWS step functions. Without giving too much specific detail, part of the request to my API includes a 'token', and my API eventually calls some URL with its response and that token.

In order to integration test the entire step function, it'd be ideal to mock that API using mmock, so that when the step function calls it, it will after a short time receive a mocked response with the token it passed in.

The flow I'm proposing is something like:

Request (includes token=XYZ header) -> mmock
mmock -> Mocked 202 response
(some short delay)
Mocked response (includes token=XYZ) -> some URL

---

As a speculative design proposal, I'd like to be able to define a request like:

```
---
request:
  method: POST
  path: "/hello"
response:
  statusCode: 202
  headers:
    Content-Type:
    - application/json
  body: '{}'
callback:
  url: http://callbackApi:3000
  delay: 500 // (milliseconds)
  headers:
    Content-Type:
    - application/json
  body: '{"token": "{{request.header.token}}", "success": true, "response": "{{fake.Digits}}"}'
```

When mmock receives a POST to `/hello`, it'd respond with the 202, and then after 500ms make an API request to `http://callbackApi:3000` with the headers + body I specified (which importantly can include request variables).

Do you think this would potentially be an appropriate use case to extend mmock to support?
