### ISSUE TITLE
Match request without parameters

### ISSUE THREAD

**Issue by NickolaySheika** [jmartin82/mmock#119]
Hey 👋  First of all, thanks for all this amazing work that you're doing!

I'm using MMock for automated tests. So far it worked pretty well. But currently, I'm facing this issue:

I have two API calls that I need to mock:
`/api/help_center`
`/api/help_center?link_id=1234`

They return different content with link_id and without it. And I need to test both cases. 

When I'm mocking like this:
```
request:
  method: GET
  path: "/api/help_center"
  queryStringParameters:
     link_id:
       - null
```
it doesn't match because clients are not sending nil/null as a parameter (most network libraries omit them if they are nil)

If I'm mocking without `queryStringParameters` then MMock simply uses one mock for ALL the requests no matter it contains `link_id` or not. 

Can you please clarify if that's possible or not?
