### ISSUE TITLE
Feature Request - support parsing of `request.path`

### ISSUE THREAD

**Issue by briantist** [jmartin82/mmock#128]
Unlike the body for example, we can't do intensive parsing of the path. The `.regex()` and `.concat()` methods don't work on the path.

The `:value` part of the path also cannot be limited to specific values, so you can't simultaneously get a particular part of path while limiting which values match.

As an example, I have a config like this:

```yaml
request:
  method: POST|PUT
  path: "/api/v1/method/create*/resource"
```

I want to match `create*`, so `create` or `create-thing` or `create-other` would be valid for that part of the path.

In the response, I want to reference that component, or part of it. I'd like to use regex maybe:

```yaml
response:
  statusCode: 200
  headers:
    Content-Type:
      - application/json
  body: 'A request to create {{request.path.regex(/create-([^/]*)/)}} has been received.'
```

However that doesn't work.

If I instead do:

```yaml
request:
  method: POST|PUT
  path: "/api/v1/method/:method/resource"
```

then I guess I can do:

```yaml
response:
  statusCode: 200
  headers:
    Content-Type:
      - application/json
  body: 'A request to {{request.path.method}} has been received.'
```
Which is something.. but not quite the same, as I can't do any string manipulation on it.

But even worse, is that the config will paths I don't want, like `/api/v1/method/delete/resource`.

It seems that my only option is hardcoding the possible permutations of paths I want to match into multiple configs, with a lot of duplication and slightly different responses. The data I need isn't in the body of the request, so it seems like I'm stuck.

**Comment by jdietrich-tc** [comment]
One of my latest PRs <https://github.com/jmartin82/mmock/pull/167> addresses this by adding a new pathVariables object to the request: 

So for your case you could have:

 ```
request:
  method: POST|PUT
  path: "/api/v1/method/:create/resource"
  pathVariables:
    create: "^create.*"
response:
  statusCode: 200
  headers:
    Content-Type:
      - application/json
  body: 'A request to {{request.path.create}} has been received.'
```

  * `/api/v1/method/create-thing/resource`
    * matches
  * `/api/v1/method/delete/resource`
    *  does not match
  * `/api/v1/method/delete-create/resource`
    *  does not match
