### ISSUE TITLE
Feature Request - allow request `path` to be a list of paths

### ISSUE THREAD

**Issue by briantist** [jmartin82/mmock#129]
It would be great if a config could match multiple paths or path patterns. That would make it possible to not duplicate a lot of config when you want to match paths that can't completely be described with a wildcard or `:value` component, or just want to match a few exact paths.

Examples:

```yaml
request:
  method: POST|PUT
  path: 
    - "/api/v1/method/create"
    - "/api/v1/method/delete"
```

```yaml
request:
  method: POST|PUT
  path: 
    - "/api/v1/method/create/*"
    - "/api/v1/method/delete*"
```

This would let the rest of sections remain the same, and possible even act differently based on path (especially in combination with #128)
