### ISSUE TITLE
Unable to escape : (colon) in request path

### ISSUE THREAD

**Issue by corte** [jmartin82/mmock#130]
This problems appears when using [URNs](https://en.wikipedia.org/wiki/Uniform_Resource_Name) for identifiers.
MMock considers it as a variable and cannot properly match the request path.

Example:
```yml
---
control:
  scenario:
    name: getNote
request:
  method: GET
  path: /api/v1/notes/urn:organization:notebook:eu:note:123
response:
  statusCode: 200
  headers:
    Content-Type:
      - "application/json"
  body: "It works"
```

This actually works because it is matching everything that starts with `/api/v1/notes/urn`, but if we try a request with another URN it will still return "It works". Or if we add another mock using another URN that will never be matched.

Suggestion. Allow escaping the colon char in some way:
```yml
request:
  method: GET
  path: /api/v1/notes/urn\:organization\:notebook\:eu\:note\:123
```
Or:
```yml
request:
  method: GET
  path: /api/v1/notes/urn::organization::notebook::eu::note::123
```
