### ISSUE TITLE
Question: how can i define multiple values of one query parameter

### ISSUE THREAD

**Issue by pkonnov** [jmartin82/mmock#132]
```yaml
---
request:
  method: "GET"
  path: "/v1/endpoint"
  queryStringParameters:
    param1:
      - "value1"
      - "value2"
response: ...
```

Log:
2022/05/13 22:21:49 Discarding mock: get_something.yaml[0] Reason: Query string not match. Actual: param1: value1, Expected: param1: value1, param1: value2
