### ISSUE TITLE
Example for regular expressions for request matching criteria

### ISSUE THREAD

**Issue by irkill** [jmartin82/mmock#176]
According to README, we can use for requests matching criteria regular expressions for field values within JSON request bodies. But I don't understand how to describe it in the config file.
Could you please give some example here and maybe create another mmock config for demonstration of this feature?

**Comment by ericchaves** [comment]
@irkill, replying a little late for future reference. From what I understand, the filter works by comparing the JSON object declared in the `request.body` section of the configuration with the JSON payload sent by the client/application.

For a match to occur, all attributes from the configured JSON must exist in the payload, **and** all the values must match. It performs a "deep" comparison between the declared JSON expression and the received payload. However, the payload may include additional attributes that are not present in the configured request JSON expression.

For example, given the sample YAML configuration below:
```yaml
request:
  method: POST
  path: /graphql
  headers:
    Content-Type:
      - application/json
  body: >
    {
      "variables": { "cid": "12345", "control": { "status": "active|blocked" } },
      "operationName": "GetCustomerData"
    }
response:
  statusCode: 200
  headers:
    Content-Type:
      - application/json
  body: >
    {
      "data": {
        "customer": {
          "id": "{{request.body.variables.cid}}",
          "name": "John Doe",
          "email": "john.doe@example.com",
          "orders": [
            {
              "id": "ord_001",
              "total": 159.99,
              "status": "completed"
            },
            {
              "id": "ord_002",
              "total": 89.99,
              "status": "processing"
            }
          ]
        }
      }
    }
```
A match would occur when all of the following conditions are met:

- The HTTP verb is `POST`.
- The path is `/graphql`.
- The `Content-Type` header is `application/json`.
- The body contains a JSON object where `operationName` is equal to `"GetCustomerData"`.
- The body contains a JSON object where `variables.cid` is equal to` "12345"`.
- The body contains a JSON object where `variables.control.status` is either `"active"` or `"blocked"`.

The following `curl` examples would match:
```bash
curl -X POST \
  -H "Content-Type: application/json" \
  -d '{
    "query": "query GetCustomerData($cid: ID!) { customer(id: $cid) { id name email orders { id total status } } }",
    "variables": {
      "cid": "12345", "control" :{ "status": "blocked"  }
    },
    "operationName": "GetCustomerData"
  }' \
  http://localhost:8083/graphql

curl -X POST \
  -H "Content-Type: application/json" \
  -d '{
    "query": "query GetCustomerData($cid: ID!) { customer(id: $cid) { id name email orders { id total status } } }",
    "variables": {
      "cid": "12345", 
      "control" :{ "status": "active",  "other": "thong" }
    },
    "operationName": "GetCustomerData"
  }' \
  http://localhost:8083/graphql
```
However, the following examples would fail with a `404` status code:
```bash
# Missing variable.control attribute
curl -X POST \
  -H "Content-Type: application/json" \
  -d '{
    "query": "query GetCustomerData($cid: ID!) { customer(id: $cid) { id name email orders { id total status } } }",
    "variables": {
      "cid": "12345"
    },
    "operationName": "GetCustomerData"
  }' \
  http://localhost:8083/graphql

# variable.cid does not match the expected value
curl -X POST \
  -H "Content-Type: application/json" \
  -d '{
    "query": "query GetCustomerData($cid: ID!) { customer(id: $cid) { id name email orders { id total status } } }",
    "variables": {
      "cid": "12346", "control" :{ "status": "active",  "other": "thong" }
    },
    "operationName": "GetCustomerData"
  }' \
  http://localhost:8083/graphql

# variable.control.status does not match the regex
curl -X POST \
  -H "Content-Type: application/json" \
  -d '{
    "query": "query GetCustomerData($cid: ID!) { customer(id: $cid) { id name email orders { id total status } } }",
    "variables": {
      "cid": "12345", "control" :{ "status": "invalid",  "other": "thing" }
    },
    "operationName": "GetCustomerData"
  }' \
  http://localhost:8083/graphql
```
