### ISSUE TITLE
Get all requested headers or a specific requested header

### ISSUE THREAD

**Issue by terlar** [jmartin82/mmock#38]
I would like to be able to just like the body be able to get requested headers in the response body.

For example:
```
request:
  method: GET
  path: /echo
response:
  statusCode: 200
  headers:
    Content-Type:
      - "application/json"
  body: >
    {
      "headers": "{{request.headers}}"
    }
```

Or to utilize specific headers:
```
request:
  method: GET
  path: /echo
response:
  statusCode: 200
  headers:
    Content-Type:
      - "application/json"
  body: >
    {
      "headers": "{{request.headers.User-Agent}}"
    }
```

This can be useful for various different testing purposes. My current use case is to check if a proxy adds/removes certain headers.
