### ISSUE TITLE
Match request header names and values with globs

### ISSUE THREAD

**Issue by terlar** [jmartin82/mmock#40]
It would be useful to have glob matching for headers also.

To match something having header with any value.

```
request:
  method: GET
  path: /echo
  headers:
    User-Agent:
      - "*"
```

Or partial value glob match:
```
request:
  method: GET
  path: /echo
  headers:
    User-Agent:
      - "curl/*"
```

It would also be useful to be able to glob match headers:
```
request:
  method: GET
  path: /echo
  headers:
    "Company-Custom-Header-*":
      - "*"
```
