### ISSUE TITLE
Multiple call to a fake function returns identical result

### ISSUE THREAD

**Issue by dgellow** [jmartin82/mmock#66]
Hi there,

I noticed that calling, let's say, `fake.Int(1000)`  multiple time gives me multiple time the exact same result in the context of a request, instead of different values. Is that the expected behaviour?

Example:
```yaml
response:
  body: |
    {
      "number1": {{fake.Int(1000)}},
      "number2": {{fake.Int(1000)}},
       "number3": {{fake.Int(1000)}}
    }
```

I'm calling this route and get the result:
```yaml
{
  "number1": 278,
  "number2": 278,
  "number3": 278
}
```

I would expect each call of the function to be randomized.
