### ISSUE TITLE
Invalid JSON is returned when using request.body."key" and multi-line strings

### ISSUE THREAD

**Issue by terlar** [jmartin82/mmock#79]
If I have a mock like this:
```
---
request:
  method: POST
  path: /test
response:
  statusCode: 201
  headers:
    Content-Type:
      - "application/json"
  body: >
    {
      "message": "{{request.body.message}}"
    }
```

And POST a JSON string like this:
```
{
  "message": "hello\nworld"
}
```

mmock will then return an invalid JSON string using a new-line instead of an escaped JSON string with `\n`. Unfortunately that is not valid JSON. E.g.

```
{
  "message": "hello
world"
}
```
