### ISSUE TITLE
Pattern *  dont work in request body strings

### ISSUE THREAD

**Issue by Carsak** [jmartin82/mmock#96]
Actual Problem:
I have simple config for POST
```
description: "Create Order POST"
request:
  method: POST
  path: /order/create/
  body: '{"email": "alma@alma.*", "product": "choco-cookies", "quantity" : 3}'
response:
  headers:
    Content-Type:
      - application/json
  statusCode: 200
  body: '{"status": "ok"}'
```
with pattern "alma@alma.*" in request body
but when I send request
```
{
    "scheme": "http",
    "host": "localhost",
    "port": "8083",
    "method": "POST",
    "path": "/order/create/",
    "queryStringParameters": {},
    "fragment": "",
    "headers": {
        "Accept-Encoding": [
            "gzip,deflate"
        ],
        "Connection": [
            "Keep-Alive"
        ],
        "Content-Length": [
            "71"
        ],
        "Content-Type": [
            "application/json"
        ],
        "User-Agent": [
            "Apache-HttpClient/4.5.8 (Java/11.0.3)"
        ]
    },
    "cookies": {},
    "body": "{\"email\" : \"alma@alma.kz\", \"product\" : \"choco-cookies\", \"quantity\" : 3}"
}
Response
```

, mmock says Error
```
"uri": "OrderCreatePositive.yaml",
            "reason": "Body not match. Actual: {\"email\" : \"alma@alma.kz\", \"product\" : \"choco-cookies\", \"quantity\" : 3}, Expected: {\"email\": \"alma@alma.*\", \"product\": \"choco-cookies\", \"quantity\" : 3}"
```

Expected:
Even email send like alma@alma.kz or alma@alma.ru or alma.alma@com the request body must match
